name: linters

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches:
      - "main"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.mjs
          token: ${{ secrets.GITHUB_TOKEN }}
